### ISSUE TITLE
testversion 1.9.6 duplicates objects 

### ISSUE THREAD

**Issue by dieterdreist** [bryceco/gomaposm.com#3]
It seems testflight v 1.9.6 will create a new object rather than raise the version, example here: https://www.openstreetmap.org/node/8184265306/history

(I updated now, just noticed I had auto updates deactivated)

**Comment by tordans** [comment]
@dieterdreist this is the Website Repo. But AFIK @bryceco can move the issue over.

**Comment by dieterdreist** [comment]
sorry for that. I was in a hurry and created it on mobile. Actually the issue can probably be closed because it refers to an old testing version.

**Comment by bryceco** [comment]
There hasn't been any change to this area of the code in a long time, so I wouldn't expect a change in behavior. Nevertheless based on the node history it does look like something weird happened, but because it's a rare occurrence we really need to find a way to reproduce the bug. Thanks!

**Comment by dieterdreist** [comment]
I did nothing special:

1. fire up GoMap!! by calling the app url (zoomed z18 over a specific location) from within another app

2. select a point, tap on „tags“, add a new tag image and paste the value. Tap done

3. Upload

the procedure of opening it through a link usually works without a problem.

**Comment by bryceco** [comment]
You can replicate the behavior? I'm unable to.

**Comment by dieterdreist** [comment]
No, I cannot replicate it. Just did the exact same thing and it worked as
it should. On the other hand, I am now using the most recent test version
i.e. not the same version.
I have also occasionally had other glitches like all nodes (also untagged
ones) with square icons (in the past), which I have not been able to
reproduce after restarting the app.
I would suggest to keep this issue closed as #worksforme
